### ISSUE TITLE
Permisos de items

### ISSUE THREAD

**Issue by slayerfat** [slayerfat/sistemaPCI#20]
@Phantom66 necesito saber todos los departamentos de la organizacion.

necesito saber los permisos que tienen cada departamento al solicitar cada rubro y sus items, es decir:

servicios generales puede pedir pasteleria?

administracion puede pedir material quirurjico?

etc.

**Comment by Phantom66** [comment]
Hasta estos momentos esas restricciones no me la han dado, aunque todo podría pedir todo, lo importante es que quede registrado quien se lo llevo, considero que no deberíamos limitarlos en ese aspecto

**Comment by slayerfat** [comment]
y que pasa si Matos dice algo al respecto?

es facil no hacer nada, pero es dificil cambiar la implementacion si hace falta.

**Comment by slayerfat** [comment]
por falta de respuesta permisos de items no estaran implementados sino para despues de 1.0
