### ISSUE TITLE
Analisis de campos en las Entidades

### ISSUE THREAD

**Issue by slayerfat** [slayerfat/sistemaPCI#46]
Necesito un analisis de integridad de la base de datos segun los cambios implementados

**Comment by slayerfat** [comment]
@Phantom66 sigo esperando por esto... era para hace una semana...

**Comment by Phantom66** [comment]
Este fin de semana te entrego eso !!

**Comment by slayerfat** [comment]
Sigo esperando 7 días después....

**Comment by slayerfat** [comment]
@Phantom66 te lo pedi hace un mes.

**Comment by slayerfat** [comment]
2 meses, ggwp.
